version: "3.5"
services:
  frontend:
    image: frontend:latest
    ports:
      - "8888:8888"
    networks:
      - dclassnet
  backend1:
    image: backend:latest
    networks:
      - dclassnet
    volumes:
      - dclassvol1:/files
  backend2:
    image: backend:latest
    networks:
      - dclassnet
    volumes:
      - dclassvol2:/files
  backend3:
    image: backend:latest
    networks:
      - dclassnet
    volumes:
      - dclassvol3:/files
networks:
  dclassnet:
    driver: host
    ipam:
      config:
        - subnet: 10.0.0.0/24
volumes:
  dclassvol1:
  dclassvol2:
  dclassvol3:

