version: "3.5"
services:
  hw4-fortune-s:
    image: hw4-fortune:latest
    volumes:
      - hw4-vol:/var/local/output
  hw4-nginx-s:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - hw4-vol:/usr/share/nginx/html
volumes:
  hw4-vol:

